#!/bin/bash

#SBATCH --job-name=cifar10_resnet
##SBATCH --output=/home/$USER/vf38_scratch/horovod/Davide/%x_%A.out
##SBATCH --error=/home/$USER/vf38_scratch/horovod/Davide/%x_%A.err
#SBATCH --account=vf38
#SBATCH --time=10:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:2
#SBATCH --partition=m3g

. /home/$USER/vf38_scratch/horovod/Davide/scripts/activate_env_main

python3 /home/$USER/vf38_scratch/horovod/Davide/models/cifar10_resnet.py
