#!/bin/bash

#SBATCH --job-name=test-sleep
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --account=vf38
#SBATCH --hint=nomultithread
#SBATCH --qos=shortq
#SBATCH --time=00:11:00
#SBATCH --mem-per-cpu=12G
#SBATCH --cpus-per-task=5
##SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=m3g
#SBATCH --mail-user=davide.marchegiani@monash.edu
#SBATCH --mail-type=BEGIN
#SBATCH --nodelist=m3g013
#SBATCH --gres=gpu:1

/home/dmar0022/vf38_scratch/horovod/Davide/scripts/horovodrun /home/dmar0022/vf38_scratch/horovod/Davide/models/hvd_fashion-mnist.py

python3 /fs03/vf38/horovod/Davide/scripts/test.py
