#!/bin/bash

if [[ $1 ]]
then
    if [[ $# > 1 ]]; then echo "Too many arguments passed. Please enter just one positional argument."; exit 1; fi
    module purge
    case $1 in
        main)
            module load cuda/11.0
        ;;
        horovod-env)
            module load cuda/11.0
            module load nccl/2.10.30-cuda11.0
        ;;
    esac
    . /fs03/vf38/dmar0022/miniconda/bin/activate /fs03/vf38/dmar0022/miniconda/conda/envs/$1
else
    . /fs03/vf38/dmar0022/miniconda/bin/activate
fi
