#!/bin/bash

# rm -r /fs03/vf38/dmar0022/miniconda/conda/envs/horovod-env

# Create yml file for the environment
env_file=horovod_env.yml
cat > $env_file <<EOF
name: horovod-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8=hffdb5ce_0_cpython
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _sysroot_linux-64_curr_repodata_hack=3=ha9d2b57_10
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py38h497a2fe_0
  - anyio=2.2.0=py38h578d9bd_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - binutils=2.35.1=hdd6e379_2
  - binutils_impl_linux-64=2.35.1=h193b22a_2
  - binutils_linux-64=2.35=h67ddf6f_30
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - c-compiler=1.1.3=h7f98852_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.1=pyhd8ed1ab_0
  - ccache=4.1=hae7a33c_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - click=7.1.2=pyh9f0ad1d_0
  - cmake=3.19.6=h3020d66_0
  - cryptography=3.4.6=py38ha5dfef3_0
  - cudatoolkit=11.0.3=h15472ef_8
  - cudnn=8.0.5.39=ha5ca753_1
  - cxx-compiler=1.1.3=h4bd325d_0
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=h9c3ff4c_0
  - freetype=2.10.4=h0708190_1
  - gcc_impl_linux-64=9.3.0=h70c0ae5_18
  - gcc_linux-64=9.3.0=hf25ea35_30
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-auth-oauthlib=0.4.1=py_2
  - gxx_impl_linux-64=9.3.0=hd87eabc_18
  - gxx_linux-64=9.3.0=h3fbe746_30
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.7.3=py38h578d9bd_0
  - ipykernel=5.5.0=py38h81c977d_1
  - ipython=7.21.0=py38h81c977d_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-packaging=0.7.12=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyter_server=1.4.1=py38h578d9bd_0
  - jupyterlab=3.0.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.3.0=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=h77966d4_10
  - krb5=1.17.2=h926e7f8_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libcurl=7.75.0=hc4aaa36_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-devel_linux-64=9.3.0=h7864c58_18
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libgomp=9.3.0=h2828fa1_18
  - libnghttp2=1.43.0=h812cca2_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.15.6=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-devel_linux-64=9.3.0=hb016644_18
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_1
  - libuv=1.41.0=h7f98852_0
  - llvm-openmp=11.0.1=h4bd325d_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=1.1.1=py38h497a2fe_3
  - mistune=0.8.4=py38h497a2fe_1003
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py38h1e0a361_2
  - mkl_fft=1.3.0=py38h5c078b8_1
  - mkl_random=1.2.0=py38hc5bc63f_1
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py38he865349_5
  - mpich=3.4.1=h846660c_104
  - multidict=5.1.0=py38h497a2fe_1
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nccl=2.8.4.1=h96e36e3_3
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.2.0=py38h578d9bd_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - nvcc_linux-64=11.0=h96e36e3_12
  - oauthlib=3.0.1=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1j=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandoc=2.12=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=7.1.2=py38hb39fc2d_0
  - pip=21.0.1=pyhd8ed1ab_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.17=pyha770c72_0
  - protobuf=3.15.6=py38h709712a_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyjwt=2.0.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.0.3=py38h2035c66_1
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rhash=1.4.1=h7f98852_0
  - rsa=4.7.2=pyh44b312d_0
  - sed=4.8=he412f7d_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.15.0=pyh9f0ad1d_0
  - sniffio=1.2.0=py38h578d9bd_1
  - sqlite=3.34.0=h74cdb3f_0
  - sysroot_linux-64=2.17=h77966d4_10
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - terminado=0.9.2=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=h21135ba_1
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=py38_cu110
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.0.5=py_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - yarl=1.6.3=py38h497a2fe_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - astunparse==1.6.3
    - bokeh==2.3.0
    - cloudpickle==1.6.0
    - flatbuffers==1.12
    - gast==0.3.3
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    # - horovod==0.21.3
    - jupyter-server-proxy==3.0.0
    - jupyterlab-nvdashboard==0.4.0
    - keras-preprocessing==1.1.2
    - opt-einsum==3.3.0
    - psutil==5.8.0
    - pynvml==8.0.4
    - pyyaml==5.4.1
    - simpervisor==0.4
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.1
    - termcolor==1.1.0
    - wrapt==1.12.1
EOF

# activate miniconda environments
. /fs03/vf38/$USER/miniconda/bin/activate

# Load modules
module purge
module load cuda/11.0
module load nccl/2.10.3-cuda11.0

# set relevant build variables for horovod
export ENV_PREFIX=$CONDA_PREFIX/conda/envs/horovod-env
export HOROVOD_CUDA_HOME=$CUDA_HOME
export HOROVOD_GPU_OPERATIONS=NCCL
export NCCL_ROOT=/usr/local/nccl/2.10.3-cuda11.0
export HOROVOD_WITH_TENSORFLOW=1

conda env create --prefix $ENV_PREFIX --file $env_file 

conda activate $ENV_PREFIX
pip install horovod --no-cache-dir --force