#!/bin/bash

#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --account=vf38
#SBATCH --gpus-per-task=1
#SBATCH --ntasks-per-node=2
#SBATCH --hint=nomultithread

#SBATCH --qos=shortq
#SBATCH --time=00:30:00
#SBATCH --job-name=hvd_fashion-mnist
#SBATCH --mem-per-cpu=12G
#SBATCH --partition=m3g,m3h
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=5

# Activate horovod environment
. /home/dmar0022/vf38_scratch/horovod/Davide/scripts/activate horovod-env

/home/dmar0022/vf38_scratch/horovod/Davide/scripts/horovodrun /home/dmar0022/vf38_scratch/horovod/Davide/models/hvd_fashion-mnist.py