#!/bin/bash

#SBATCH --job-name=hvd_fashion-mnist
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --account=vf38
#SBATCH --hint=nomultithread
#SBATCH --qos=shortq
#SBATCH --time=00:10:00
#SBATCH --mem-per-cpu=12G
#SBATCH --cpus-per-task=5
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=2
#SBATCH --gres=gpu:2
##SBATCH --nodes=2
#SBATCH --gpus-per-task=1
#SBATCH --ntasks-per-node=2
#SBATCH --partition=m3g
##SBATCH --nodelist=m3g[000,001]


# Activate horovod environment
. /home/dmar0022/vf38_scratch/horovod/Davide/scripts/activate horovod-env

# echo ciao mamma
/home/dmar0022/vf38_scratch/horovod/Davide/scripts/horovodrun /home/dmar0022/vf38_scratch/horovod/Davide/models/hvd_fashion-mnist.py
