#!/bin/bash

#SBATCH --job-name=test
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --account=vf38
#SBATCH --hint=nomultithread
#SBATCH --qos=shortq
#SBATCH --time=00:10:00
#SBATCH --mem-per-cpu=12G
#SBATCH --cpus-per-task=5
#SBATCH --ntasks=2
#SBATCH --gres=gpu:2
##SBATCH --nodes=1
#SBATCH --gpus-per-task=1
#SBATCH --ntasks-per-node=2
#SBATCH --partition=m3g,m3h
#SBATCH --mail-user=davide.marchegiani@monash.edu
#SBATCH --mail-type=BEGIN

# Activate horovod environment
. /home/dmar0022/vf38_scratch/horovod/Davide/scripts/activate horovod-env
echo "Cuda visible devices before python script (with mpi and -genv CUDA_VISIBLE_DEVICES '0,1' flag ): ${CUDA_VISIBLE_DEVICES}"

#/home/dmar0022/vf38_scratch/horovod/Davide/scripts/horovodrun /home/dmar0022/vf38_scratch/horovod/Davide/scripts/test.py
mpirun -bind-to none -map-by slot -genv NCCL_DEBUG WARN -genvlist LD_LIBRARY_PATH,PATH -np 2 -hosts m3g011:2  python3 /fs03/vf38/horovod/Davide/scripts/test.py
# python3 /home/dmar0022/vf38_scratch/horovod/Davide/scripts/test.py
