#!/bin/bash

# Get info about current job
info=$(cat /fs03/vf38/horovod/Davide/scripts/hvd_fashion-mnist-20841112.out)

# Get total number of gpus allocated to current job
ngpus=$(grep -Po "(?<=gres/gpu=)\d*" <<< $info)
# If gpus are not found raise return an error and exit the program
if [[ -z "$ngpus" ]]
then
    echo "No gpus found. Please request at least 1 gpu when you run horovod."
    exit 10
else
# Otherwise bind number of horovod processes to tot number of gpus
    options+="-np $ngpus "
fi

# Find computing nodes and allocated resources
str=($(echo "$info" | grep -Po "(?<=AdminComment=).*?(?=\s)" | tr ";" " "))
for s in ${str[@]} #For all the different computing nodes' strings
do
    gpus=($(echo "$s" | grep -Po "(?<=gpu:).*?(?=\()" | tr "," " "))
    n=0
    if [[ "$gpus" ]] #If there is any gpu associated with the node(s)
    then
        # Get total gpus associated with the node(s)
        for gpu in ${gpus[@]} 
        do
            (( n+=$(echo "$gpu" | grep -Po "(?<=:)\d+|^\d+") ))
        done
        host=$(grep -Po "(?<=^\|).*?(?=\|)" <<< $s)
        host=($(grep -Po "(^m3.*?(?=,m3)|(?<=,)m3.*(?=,m3)|m3.*?$)"<<<$host))
        for h in ${host[@]} #For all the nodes' names/numbers
        do  
            hname=$(grep -Po "^m3."<<<$h) #Get the name
            # Get the ID number(s)
            if [[ $h =~ m3.[[:digit:]]{3} ]] #If there is only one number associated
            then
                hosts+=$(printf "${hname}${h:3:3}:${n}," ) #Get host ID
            else
                # Get all the ID numbers
                hid=($(echo "$h" | grep -Po "(?<=m3.\[).*(?=\])" | tr "," " "))
                for id in ${hid[@]}
                do
                    [[ "$id" =~ ^(.{3})-?(.{3})? ]]
                    if [[ ${BASH_REMATCH[2]} ]]
                    then
                        hnum=$(seq ${BASH_REMATCH[1]} ${BASH_REMATCH[2]})
                    else
                        hnum=${BASH_REMATCH[1]##*(0)}
                    fi
                    for num in $hnum
                    do
                        # hosts+=$(printf "${hname}%03d:${n}," $num)
                        echo $num
                    done
                done
            fi
        done
    fi
done

# Bind computing nodes and allocated resources
options+="-hosts ${hosts%,} "

echo "mpirun ${options}"
# mpirun ${options} python3 $(readlink -f $1)
